### ISSUE TITLE
MDS rubrics

### ISSUE THREAD

**Issue by mgelbart** [CPSC340/classy#17]
- We will need to support an extra level of nesting, as in [this rubric](https://github.com/UBC-MDS/public/blob/master/rubric/rubric_quality.md) having two parts each worth 50%.
- We already have some horrible code that parses this info literally from the .md files. But you can just throw it in a JSON or something for now. 
- [Example assignment](https://github.com/UBC-MDS/DSCI_572_sup-learn-2_public/blob/master/labs/lab1/lab1.ipynb)

The grading scheme:

```python
UBC_LETTER_GRADES = {
    (90,100): "A+",
    (85,89) : "A",
    (80,84) : "A-",
    (76,79) : "B+",
    (72,75) : "B",
    (68,71) : "B-",
    (64,67) : "C+",
    (60,63) : "C",
    (55,59) : "C-",
    (50,54) : "D",
    (0,49)  : "F"
}
```

Each letter grade gets mapped to the **midpoint** of its range. E.g. an A+ turns into 95%. It is then scaled by the "out of" for that question in the assignment, and this allows you to get an overall grade for the assignment.

- You may need to work on Reid's code in Classy where students login and see their grades. We'll need to change the format slightly for them to see all this. Here's an example of what an MDS student currently sees. We need something similar but it doesn't have to be identical, nor does it have to be as detailed for the prototype.

#### Writing (worth 5%)

| Rubric                        | Raw Score   | Scaled Score   |   Points Earned |   Out Of |
|-------------------------------|-------------|----------------|-----------------|----------|
| Writing -- Grammar & Spelling | A+          | 95%            |           2.375 |      2.5 |
| Writing -- Length             | A+          | 95%            |           2.375 |      2.5 |
| **Total**                     |             |                |           4.75  |      5   |

#### Question 6.3

| Rubric    | Raw Score   | Scaled Score   |   Points Earned |   Out Of |
|-----------|-------------|----------------|-----------------|----------|
| Reasoning | A+          | 95%            |             3.8 |        4 |

## Overall Evaluation

| Exercise Name                |   Points Earned |   Out Of |
|------------------------------|-----------------|----------|
| Writing (worth 5%)           |           4.75  |        5 |
| ... | ... | ... |
| 6.3                          |           3.8   |        4 |
| ... | ... | ... |
| **Total**                    |          93.835 |      100 |

Final grade: 93.8/100.0 = **94%**

**Comment by mgelbart** [comment]
I suggest dealing with the letter grades first. And then later we can talk about the nested rubrics.

**Comment by jopika** [comment]
Letter grades and optional rubric items are handled completely.

Currently missing:
~Nested Rubrics~ (not implementing)
Raw grade inputs
