### ISSUE TITLE
Full run-through

### ISSUE THREAD

**Issue by mgelbart** [CPSC340/classy#26]
Here is what needs to work:

- Create a deliverable
- Provision repos that are seeded from a subdirectory (possibly using scheduler)
- Release deliverable
- Close repos (remove write access), possibly using scheduler
- Run through grading (need a "next" button per #22 )
- Students to view grades for a deliverable
- Students to view grades for the whole course #24

**Comment by jopika** [comment]
- [x] Create a deliverable
- [x] Provision repos that are seeded from a subdirectory
- [x] With a scheduler
- [x] Release deliverable
- [x] Close repos (remove write access)
- [x] With a scheduler
- [x] Run through grading (need a "next" button per #22 )
- [x] Students to view grades for a deliverable
- [x] Students to view grades for the whole course #24

**Comment by jopika** [comment]
Completed as of latest commit in `release/mds`
