### ISSUE TITLE
Use Collaborators to grant Repository Access

### ISSUE THREAD

**Issue by jopika** [CPSC340/classy#5]
Using teams for each assignment and repository causes excessive team creation.

Migrating to Collaborators to grant access to repositories will aide this issue.

**Comment by mgelbart** [comment]
- There should be a switch/flag to toggle between these modes. It doesn't matter to me if this is in the UI or just in the code for now. It doesn't matter to me if this is at the course level or deliverable level (for now). How it works:

- No team ever create for a student-deliverable pair.
- Instead, just add them (everyone in the group) as a collaborator, first with write access and later with read access.
- The staff Team can still be used on each repo (no change needed).

**Comment by jopika** [comment]
Team creation seems to occur on Github during repository creation.

Using collaborators, the teams are still created, but they are never used.
