### ISSUE TITLE
Upload column of marks using a CSV

### ISSUE THREAD

**Issue by jopika** [CPSC340/classy#64]
Canvas Quizzes should be importable using a CSV (as a current workaround)

**Comment by mgelbart** [comment]
This feature seems to exist. @jopika will test it out and make sure it works as expected.

**Comment by jopika** [comment]
Addressed in: 51fe1df0da6d3442345acab74ddbc2a0a2f2ff60

Seems to be working as intended, with one caveat of not having rubrics which causes the final grades table to be a bit wonky. 

Current workaround is to either insert a dummy rubric into Classy's Edit Deliverable UI, or create a simple small "main file" for the assignment and let the rubric generator handle it.
